# Generated by Django 2.0.6 on 2018-06-03 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250, verbose_name='Question Text')),
                ('question_type', models.CharField(choices=[('Multiple Choice', 'Multiple Choice'), ('Freetext', 'Freetext')], max_length=250, verbose_name='Question Type')),
                ('position', models.IntegerField(default=0, verbose_name='Question Position')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(max_length=250, verbose_name='Response text')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Question')),
            ],
        ),
    ]
