# Generated by Django 2.0.6 on 2018-06-10 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=2500)),
                ('active', models.NullBooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='response',
            name='active',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('Freetext', 'Freetext'), ('Multiple Choice', 'Multiple Choice')], max_length=250, verbose_name='Question Type'),
        ),
        migrations.AddField(
            model_name='question',
            name='questionnaire',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Questionnaire'),
            preserve_default=False,
        ),
    ]
